#norminette-beta srcs 
#norminette-beta Makefile inc
#norminette-beta Get_Path bmp_to_bxpm ../libs/libft libbxpm ../libs/libpf ../libs/libtp

norminette-beta srcs/ai_attack.c \
srcs/ai_movement.c \
srcs/animate_wsprite.c \
srcs/args.c \
srcs/blit_bxpm.c \
srcs/blit_entity.c \
srcs/camera.c \
srcs/clock.c \
srcs/collision_detection.c \
srcs/color_and_brightness.c \
srcs/compute_vline.c \
srcs/crosshair_position.c \
srcs/doom.c \
srcs/draw2.c \
srcs/draw_bullet_holes.c \
srcs/draw_ceiling.c \
srcs/draw_crosshair.c \
srcs/draw_entity.c \
srcs/draw_floor.c \
srcs/draw_floor_and_ceiling.c \
srcs/draw_hud.c \
srcs/draw_neighbor_wall.c \
srcs/draw_portal_texture.c \
srcs/draw_projectile.c \
srcs/draw_skybox.c \
srcs/draw_wall.c \
srcs/draw_weapon.c \
srcs/draw_wsprites.c \
srcs/endless.c \
srcs/find_sector.c \
srcs/fps.c \
srcs/free.c \
srcs/free1.c \
srcs/free2.c \
srcs/free3.c \
srcs/game_loading.c \
srcs/game_over.c \
srcs/game_pause.c \
srcs/game_quit.c \
srcs/get_entity_state.c \
srcs/help.c \
srcs/hud_utils.c \
srcs/icon.c \
srcs/init.c \
srcs/horizontal_collision.c

#norminette-beta srcs/init_alfred.c \
#srcs/init_alfred2.c \
#srcs/init_barrel.c \
#srcs/init_entity.c \
#srcs/init_game_mode.c \
#srcs/init_glock.c \
#srcs/init_inventory.c \
#srcs/init_kar.c \
#srcs/init_lamp.c \
#srcs/init_launcher.c \
#srcs/init_meat_hook.c \
#srcs/init_minigun.c \
#srcs/init_minimap.c \
#srcs/init_player.c \
#srcs/init_render.c \
#srcs/init_rift.c \
#srcs/init_scale.c \
#srcs/init_sdl.c \
#srcs/init_shotgun.c \
#srcs/init_slope.c \
#srcs/init_spooky.c \
#srcs/init_spooky2.c \
#srcs/init_textures.c \
#srcs/init_torch.c \
#srcs/init_weapons.c \
#srcs/keys.c \
#srcs/line.c \
#srcs/malloc_texture_pos.c \
#srcs/map_events.c \
#srcs/math1.c \
#srcs/math2.c \
#srcs/math3.c \
#srcs/math4.c \
#srcs/math5.c \
#srcs/math6.c \
#srcs/math7.c \
#srcs/math8.c \
#srcs/minimap.c \
#srcs/movement.c \
#srcs/object_collision.c \
#srcs/orientation.c \
#srcs/parse_map_events.c \
#srcs/parse_map_header.c \
#srcs/parse_map_sector.c \
#srcs/parse_map_sprite.c \
#srcs/precompute_buy_menu.c \
#srcs/precompute_entities.c \
#srcs/precompute_projectiles.c \
#srcs/precompute_skybox.c \
#srcs/precompute_walls.c \
#srcs/precompute_weapon.c \
#srcs/project_entity.c \
#srcs/project_wall.c \
#srcs/projectile_contact.c \
#srcs/protalloc.c \
#srcs/put_pixels.c \
#srcs/random.c \
#srcs/read_map.c \
#srcs/reload_map.c \
#srcs/skybox_ceiling_vline.c \
#srcs/skybox_floor_vline.c \
#srcs/skybox_wall_vline.c \
#srcs/sound.c \
#srcs/spawn_entity.c \
#srcs/update_screen.c \
#srcs/validate_map1.c \
#srcs/validate_map2.c \
#srcs/vertical_line.c \
#srcs/wall_slide.c \
#srcs/wall_to_screen_xz.c
